# Generated by Django 5.2 on 2025-04-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_restaurante_options_restaurante_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cocina',
                'verbose_name_plural': 'Tipos de Cocina',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='restaurante',
            name='tipos_cocina',
            field=models.ManyToManyField(blank=True, related_name='restaurantes', to='api.tipococina', verbose_name='Tipos de Cocina'),
        ),
    ]
