# Generated by Django 5.2 on 2025-04-23 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_producto_restaurante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('en_camino', 'En Camino'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado de la Orden')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de la Orden')),
                ('direccion_envio', models.TextField(verbose_name='Dirección de Envío')),
                ('instrucciones_especiales', models.TextField(blank=True, null=True, verbose_name='Instrucciones Especiales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='api.envio', verbose_name='Opción de Envío')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='api.metodopago', verbose_name='Método de Pago')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='api.restaurante', verbose_name='Restaurante')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario al momento de la Orden')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal del Item')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_orden', to='api.producto', verbose_name='Producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.orden', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Detalle de Orden',
                'verbose_name_plural': 'Detalles de Órdenes',
                'unique_together': {('orden', 'producto')},
            },
        ),
    ]
