# Generated by Django 5.2 on 2025-04-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_orden_detalleorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Actualización'),
        ),
    ]
