# Generated by Django 5.2 on 2025-04-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_detalleorden_created_at_detalleorden_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total de la Orden'),
        ),
    ]
