# Generated by Django 5.2 on 2025-04-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_orden_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Cliente'),
        ),
        migrations.AddField(
            model_name='orden',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Cliente'),
        ),
        migrations.AddField(
            model_name='orden',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Cliente'),
        ),
    ]
