# Generated by Django 5.2 on 2025-04-28 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_categoria_restaurante_alter_orden_usuario_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('restaurante', 'slug')},
        ),
    ]
